# Generated by Django 5.2.1 on 2025-06-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual interest rate as a percentage",
                        max_digits=5,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("shares", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "dividend_yield",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual dividend yield as a percentage",
                        max_digits=5,
                    ),
                ),
            ],
        ),
    ]
