# Generated by Django 5.2.1 on 2025-06-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_bankaccount_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="income",
            name="date",
        ),
        migrations.AddField(
            model_name="income",
            name="frequency",
            field=models.CharField(
                choices=[("W", "Weekly"), ("M", "Monthly"), ("Y", "Yearly")],
                default="M",
                max_length=1,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="income",
            name="name",
            field=models.CharField(default="Unnamed", max_length=100),
            preserve_default=False,
        ),
    ]
