# Generated by Django 5.2.1 on 2025-06-03 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_expand_liability"),
        ("finance", "0003_remove_income_date_income_frequency_income_name"),
    ]

    operations = []
